spring:
  application:
    name: "kafka-streams-poc"

  data:
    mongodb:
      host: "localhost"
      port: "27017"
      username: "root"
      password: "temporal"
      database: "kafka"
      authentication-database: "admin"

  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    producer:
      acks: "all"
      retries: 3
      linger-ms: 2
    consumer:
      auto-offset-reset: "earliest"
      enable-auto-commit: "false"
    streams:
      threads: 1
    group-ids:
      members-new: "${spring.application.name}.members.new"
      commercial-orders-new: "${spring.application.name}.commercial-orders.new"
    topics:
      members-new: "t.members.new"
      products-new: "t.products.new"
      commercial-orders-new: "t.commercial-orders.new"
      commercial-orders-converted: "t.commercial-orders.converted"
      commercial-order-lines-split: "t.commercial-order-lines.split"
      purchase-order-lines-aggregated: "t.purchase-order-lines.aggregated"
      purchase-orders-generated: "t.purchase-order.generated"
